/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package MainPackage;
import javax.swing.ImageIcon;
/**
 * @AUTHORS: 
 * Cagubcub, John Romaine
 * Katigbac, Cyrus
 * Lugo, Hans Francis
 * Pilien, Richard
 * Subido, Joshua
 */
public class MainGui extends javax.swing.JFrame {
    
    automataSolver aSolver = new automataSolver();
    automataSimulation aSim = new automataSimulation();
    pdaDisplay pDisplay;
    
    ImageIcon imageDFA0 = new ImageIcon("DFA0.png");
    ImageIcon imageDFA1 = new ImageIcon("DFA1.png");
    String regEx1 = "(aa+bb)(a+b)* (a+b + ab + ba) (a+b+ab+ba)* (aa+bab)* (a+b+aa) (a+b+bb+aa)*";
    String regEx2 = "((101) + (111)* + (100)) + (1+0+11)* (1+0+01)* (111+000+101) (1+0)*";
    boolean isDFA1;
    
    String selectedString = "";
    
    /** Creates new form MainGui */
    public MainGui() {
        initComponents();
        setResizable(false);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dfaPanel = new javax.swing.JPanel();
        DFAimg = new javax.swing.JLabel();
        RegexLabel = new javax.swing.JLabel();
        cfgDisplay = new javax.swing.JPanel();
        cfgLabel = new javax.swing.JLabel();
        verifyButton = new javax.swing.JButton();
        StartSimulation = new javax.swing.JButton();
        stringInput1 = new javax.swing.JTextField();
        stringResult1 = new javax.swing.JLabel();
        stringInput2 = new javax.swing.JTextField();
        stringResult2 = new javax.swing.JLabel();
        stringInput3 = new javax.swing.JTextField();
        stringResult3 = new javax.swing.JLabel();
        stringInput4 = new javax.swing.JTextField();
        stringResult4 = new javax.swing.JLabel();
        stringInput5 = new javax.swing.JTextField();
        stringResult5 = new javax.swing.JLabel();
        StartSimulation1 = new javax.swing.JButton();
        StartSimulation2 = new javax.swing.JButton();
        StartSimulation3 = new javax.swing.JButton();
        StartSimulation4 = new javax.swing.JButton();
        displayPDA = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("RegEx1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("RegEx2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        dfaPanel.setBackground(new java.awt.Color(0, 0, 0));

        DFAimg.setBackground(new java.awt.Color(0, 0, 0));
        DFAimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout dfaPanelLayout = new javax.swing.GroupLayout(dfaPanel);
        dfaPanel.setLayout(dfaPanelLayout);
        dfaPanelLayout.setHorizontalGroup(
            dfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DFAimg, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
        );
        dfaPanelLayout.setVerticalGroup(
            dfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dfaPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(DFAimg, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RegexLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        cfgDisplay.setBackground(new java.awt.Color(255, 255, 255));

        cfgLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cfgLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cfgLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cfgLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout cfgDisplayLayout = new javax.swing.GroupLayout(cfgDisplay);
        cfgDisplay.setLayout(cfgDisplayLayout);
        cfgDisplayLayout.setHorizontalGroup(
            cfgDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cfgDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cfgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );
        cfgDisplayLayout.setVerticalGroup(
            cfgDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cfgDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cfgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        verifyButton.setText("Verify");
        verifyButton.setEnabled(false);
        verifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyButtonActionPerformed(evt);
            }
        });

        StartSimulation.setText("Simulate");
        StartSimulation.setEnabled(false);
        StartSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartSimulationActionPerformed(evt);
            }
        });

        stringInput1.setEnabled(false);
        stringInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stringInput1ActionPerformed(evt);
            }
        });

        stringInput2.setEnabled(false);

        stringInput3.setEnabled(false);

        stringInput4.setEnabled(false);

        stringInput5.setEnabled(false);

        StartSimulation1.setText("Simulate");
        StartSimulation1.setEnabled(false);
        StartSimulation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartSimulation1ActionPerformed(evt);
            }
        });

        StartSimulation2.setText("Simulate");
        StartSimulation2.setEnabled(false);
        StartSimulation2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartSimulation2ActionPerformed(evt);
            }
        });

        StartSimulation3.setText("Simulate");
        StartSimulation3.setEnabled(false);
        StartSimulation3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartSimulation3ActionPerformed(evt);
            }
        });

        StartSimulation4.setText("Simulate");
        StartSimulation4.setEnabled(false);
        StartSimulation4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartSimulation4ActionPerformed(evt);
            }
        });

        displayPDA.setText("open PDA");
        displayPDA.setEnabled(false);
        displayPDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayPDAActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cfgDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(StartSimulation)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(stringInput1)
                                        .addComponent(stringInput2)
                                        .addComponent(stringInput3)
                                        .addComponent(stringInput4)
                                        .addComponent(stringInput5)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(stringResult1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(stringResult2)
                                                .addComponent(stringResult3)
                                                .addComponent(stringResult4)
                                                .addComponent(stringResult5)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButton1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButton2)))
                                            .addGap(0, 0, Short.MAX_VALUE)))
                                    .addComponent(StartSimulation1)
                                    .addComponent(StartSimulation2)
                                    .addComponent(StartSimulation3)
                                    .addComponent(StartSimulation4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(verifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(displayPDA)
                                    .addComponent(clearButton))))
                        .addGap(28, 28, 28)
                        .addComponent(dfaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(RegexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(displayPDA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stringInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verifyButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StartSimulation)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(stringResult1)
                                .addComponent(clearButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stringInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StartSimulation1)
                            .addComponent(stringResult2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stringInput3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StartSimulation2)
                            .addComponent(stringResult3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stringInput4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StartSimulation3)
                            .addComponent(stringResult4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stringInput5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StartSimulation4)
                            .addComponent(stringResult5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cfgDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dfaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DFAimg.setIcon(imageDFA0);
        RegexLabel.setText(regEx1);
        verifyButton.setEnabled(true);
        displayPDA.setEnabled(true);
        isDFA1 = true;
        this.pDisplay = new pdaDisplay(isDFA1);
        stringInput1.setEnabled(true);
        stringInput2.setEnabled(true);
        stringInput3.setEnabled(true);
        stringInput4.setEnabled(true);
        stringInput5.setEnabled(true);
        
        cfgLabel.setText("<html> S -> WZXZZYZ <br/> W -> aa | bb <br/> X -> a | b | ab | ba <br/> Y -> a | b | aa <br/> Z -> aZ | bZ | ^ </html>");
        
        stringInput1.setText("");
        stringInput2.setText("");
        stringInput3.setText("");
        stringInput4.setText("");
        stringInput5.setText("");
        stringResult1.setText("");
        stringResult2.setText("");
        stringResult3.setText("");
        stringResult4.setText("");
        stringResult5.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DFAimg.setIcon(imageDFA1);
        RegexLabel.setText(regEx2);
        verifyButton.setEnabled(true);
        displayPDA.setEnabled(true);
        isDFA1 = false;
        this.pDisplay = new pdaDisplay(isDFA1);
        stringInput1.setEnabled(true);
        stringInput2.setEnabled(true);
        stringInput3.setEnabled(true);
        stringInput4.setEnabled(true);
        stringInput5.setEnabled(true);
        
        cfgLabel.setText("<html>S -> X | WWYW <br/> X -> 101 | 100 | Z <br/> Y -> 111 | 000 | 101 <br/> Z -> 111Z | ^ <br/> W -> 1W | 0W | ^ </html>");
        
        stringInput1.setText("");
        stringInput2.setText("");
        stringInput3.setText("");
        stringInput4.setText("");
        stringInput5.setText("");
        stringResult1.setText("");
        stringResult2.setText("");
        stringResult3.setText("");
        stringResult4.setText("");
        stringResult5.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void verifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyButtonActionPerformed
       String regIn1 = stringInput1.getText();
       String regIn2 = stringInput2.getText();
       String regIn3 = stringInput3.getText();//why does this code look so bad. well because loops will need the button to be pressed every time.
       String regIn4 = stringInput4.getText();//doing it like this makes it verify all at once. yes it looks bad, i don't like it. i should've looked for a better way to do this - romaine
       String regIn5 = stringInput5.getText();
       if (isDFA1 == true){
        stringResult1.setText(aSolver.reg1(regIn1));
        stringResult2.setText(aSolver.reg1(regIn2));
        stringResult3.setText(aSolver.reg1(regIn3));
        stringResult4.setText(aSolver.reg1(regIn4));
        stringResult5.setText(aSolver.reg1(regIn5));
       }
       else{
       stringResult1.setText(aSolver.reg2(regIn1));
       stringResult2.setText(aSolver.reg2(regIn2));
       stringResult3.setText(aSolver.reg2(regIn3));
       stringResult4.setText(aSolver.reg2(regIn4));
       stringResult5.setText(aSolver.reg2(regIn5));
       } //i did try to like put this in a function so it didn't look so bad. it didn't work out.
       StartSimulation1.setEnabled(true);
       StartSimulation.setEnabled(true);
       StartSimulation2.setEnabled(true);
       StartSimulation3.setEnabled(true);
       StartSimulation4.setEnabled(true);
    }//GEN-LAST:event_verifyButtonActionPerformed

    private void stringInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stringInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stringInput1ActionPerformed

    private void StartSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartSimulationActionPerformed
        pickSimulation(stringInput1.getText());
    }//GEN-LAST:event_StartSimulationActionPerformed

    private void pickSimulation(String stringIn){
        if (isDFA1 == true)
            aSim.startReg1(stringIn);
        else 
            aSim.startReg2(stringIn);
    }
    
    
    private void displayPDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayPDAActionPerformed
        pDisplay.run();
    }//GEN-LAST:event_displayPDAActionPerformed

    private void StartSimulation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartSimulation1ActionPerformed
        pickSimulation(stringInput2.getText());
    }//GEN-LAST:event_StartSimulation1ActionPerformed

    private void StartSimulation2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartSimulation2ActionPerformed
        pickSimulation(stringInput3.getText());
    }//GEN-LAST:event_StartSimulation2ActionPerformed

    private void StartSimulation3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartSimulation3ActionPerformed
        pickSimulation(stringInput4.getText());
    }//GEN-LAST:event_StartSimulation3ActionPerformed

    private void StartSimulation4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartSimulation4ActionPerformed
        pickSimulation(stringInput5.getText());
    }//GEN-LAST:event_StartSimulation4ActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
stringInput1.setText("");
        stringInput2.setText("");
        stringInput3.setText("");
        stringInput4.setText("");
        stringInput5.setText("");
        stringResult1.setText("");
        stringResult2.setText("");
        stringResult3.setText("");
        stringResult4.setText("");
        stringResult5.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DFAimg;
    private javax.swing.JLabel RegexLabel;
    private javax.swing.JButton StartSimulation;
    private javax.swing.JButton StartSimulation1;
    private javax.swing.JButton StartSimulation2;
    private javax.swing.JButton StartSimulation3;
    private javax.swing.JButton StartSimulation4;
    private javax.swing.JPanel cfgDisplay;
    private javax.swing.JLabel cfgLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel dfaPanel;
    private javax.swing.JButton displayPDA;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField stringInput1;
    private javax.swing.JTextField stringInput2;
    private javax.swing.JTextField stringInput3;
    private javax.swing.JTextField stringInput4;
    private javax.swing.JTextField stringInput5;
    private javax.swing.JLabel stringResult1;
    private javax.swing.JLabel stringResult2;
    private javax.swing.JLabel stringResult3;
    private javax.swing.JLabel stringResult4;
    private javax.swing.JLabel stringResult5;
    private javax.swing.JButton verifyButton;
    // End of variables declaration//GEN-END:variables

    public String ToString(boolean input){
        if (input == true)
            return "true";
        else if (input == false)
            return "false";
        else
            return null;
    }
    
}
